"""update user table

Revision ID: 4b97d48e9cfa
Revises: a06baebfbcc8
Create Date: 2024-05-31 23:11:39.678435

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b97d48e9cfa"
down_revision: Union[str, None] = "a06baebfbcc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("active_user", sa.Boolean(), nullable=True))
    op.drop_index(
        "username_index",
        table_name="user",
        postgresql_with={"deduplicate_items": "true"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "username_index",
        "user",
        ["username"],
        unique=False,
        postgresql_with={"deduplicate_items": "true"},
    )
    op.drop_column("user", "active_user")
    # ### end Alembic commands ###
