"""add new columns to user table

Revision ID: db0944876f9f
Revises: 951e791e82b6
Create Date: 2024-06-18 23:10:43.994016

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db0944876f9f"
down_revision: Union[str, None] = "951e791e82b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sa.String(), nullable=False))
    op.add_column("user", sa.Column("active", sa.Boolean(), nullable=False))
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_unique_constraint(None, "user", ["email"])
    op.drop_column("user", "active_user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "active_user", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "user", type_="unique")
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("user", "active")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
